using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GreenScreenDouble : MonoBehaviour
{
    [SerializeField]
    GreenScreenManager leftGreenScreenManager;
    [SerializeField]
    GreenScreenManager rightGreenScreenManager;

    [SerializeField]
    public Color keyColors = new Color(0.0f, 1.0f, 0.0f, 1);

    [SerializeField]
    [Range(0, 1)]
    public float range = 0.42f;

    [SerializeField]
    [Range(0, 1)]
    public float smoothness = 0.08f;

    [SerializeField]
    [Range(0, 1)]
    public float whiteClip = 1.0f;

    [SerializeField]
    [Range(0, 1)]
    public float blackClip = 0.0f;

    [SerializeField]
    [Range(0, 5)]
    public int erosion = 0;

    [SerializeField]
    [Range(0, 1)]
    public float spill = 0.1f;

    private void OnEnable()
    {
        SetManager(leftGreenScreenManager);
        SetManager(rightGreenScreenManager);
    }

    private void OnValidate()
    {
        SetManager(leftGreenScreenManager);
        SetManager(rightGreenScreenManager);
    }

    private void SetManager(GreenScreenManager pManager)
    {
        pManager.keyColors = keyColors;
        pManager.range = range;
        pManager.smoothness = smoothness;
        pManager.whiteClip = whiteClip;
        pManager.blackClip = blackClip;
        pManager.erosion = erosion;
        pManager.spill = spill;
    }
}
